language: python

os: linux

dist: focal

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

compiler: clang

branches:
  only:
  - /.*/

install:
  - pip install poetry codecov
  - poetry build
  - poetry install

script:
  - travis_wait 40 poetry run pytest --doctest-glob='*.rst' docs/ # Check .rst documentation
  - travis_wait 40 poetry run pytest -x --doctest-modules --cov=sem/ # Check code and docstrings
  - codecov
