[tool.poetry]
name = "sem"
version = "0.2.3"
description = "A simulation execution manager for ns-3"
authors = ["Davide Magrin <magrinda@dei.unipd.it>"]
license = "GPL-2.0-only"
readme = "README.md"
repository = "https://github.com/signetlabdei/sem"
homepage = "https://github.com/signetlabdei/sem"
keywords = ["ns-3","simulation","execution"]

[tool.poetry.dependencies]
python = "^3.5" 
tqdm = "*"
gitpython = "*"
drmaa = "*"
tinydb = "*"
xarray = "*"
numpy = "*"
click = "*"
salib = "^1.3.8"

[tool.poetry.dev-dependencies]
sphinx = "*"
pylint = "*"
sphinxcontrib-napoleon = "*"
pytest-cov = "*"
pytest = "*"
matplotlib = "*"
graphviz = "*"
scipy = "*"
pygments = "*"
pytest-xdist = "*"
importmagic = "*"
flake8 = "*"
check-manifest = { version = "*", optional = true }

[tool.poetry.scripts]
sem = 'sem:cli'

[tool.poetry.extras]
dev = ["check-manifest"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
